name: Build Elm

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: infomark/elm:0.19.0git

    steps:
      - uses: actions/checkout@v3
      - name: Checkout submodules
        run: git submodule update --init --recursivek

      - name: Run build
        run: elm-app build
