name: Build Elm

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: infomark/elm:0.19.1

    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true

      - name: Run build
        run: elm-app build
